export default [
  'Usability engineering',
  'User-centred design',
  'User journey',
  'Lean AI',
  'Test-driven development',
  'Experience design',
  'React',
  "Agile",
  "Python",
  "JavaScript",
  "spaCy",
  "AWS",
  'Modular Code',
  'Machine learnng',
  'Data science',
  'Intelligence',
  'NLP',
  'Big data',
  'Analytics',
  'Data visualization',
  'Customer satisfaction',
  'Conversational AI',
  'Focus on affordance',
  'Forward thinking',
  'Anaconda 3',
  'Internet of things',

  // 'Progressive disclosure',
  // 'Red route',
  // 'Stakeholder Interviews',
  // 'Iterative design',
  // 'Information scent',
  // 'The Double Diamond',
  // 'Principles Over Standards',
  // 'Accessibility First',
  // 'Functional Programming',
  // 'Offline Web Apps',
  // 'Shadow DOM',
  // 'Continuous integration',
  // 'Pair programming',
  // 'Module bundlers',
  // 'Redux',
  // 'Jest',
  // 'Visual regression testing',
  // 'Snapshot testing',
  // 'Type inference',
  // 'RxJS',
  // 'Leadership',
  // 'Async functions',
]
